name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build step
        run: echo "Building frontend..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Deploy to Frontend Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.FRONTEND_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull louislam/uptime-kuma:1
            sudo docker stop uptime-kuma || true
            sudo docker rm uptime-kuma || true
            sudo docker run -d --restart=always \
            -p 80:3001 \
            -v uptime-kuma:/app/data \
            --name uptime-kuma \
            louislam/uptime-kuma:1
